server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:commandes
    driverClassName: org.h2.Driver
    username: khalil
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.example.commandes: DEBUG
